# Generated by Django 5.1.3 on 2025-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Numer 11-cyfrowy, np. 30181700000', max_length=20, unique=True, verbose_name='Numer inwentarzowy')),
                ('equipment_type', models.CharField(choices=[('SET', 'Zestaw komputerowy'), ('PC', 'Komputer'), ('MONITOR', 'Monitor'), ('LAPTOP', 'Laptop'), ('PROJECTOR', 'Rzutnik'), ('ACCESSORY', 'Akcesoria')], default='SET', max_length=20, verbose_name='Rodzaj sprzętu')),
                ('equipment_name', models.CharField(help_text="Np. Lenovo P360, Dell OptiPlex, Iiyama 24'' itd.", max_length=255, verbose_name='Nazwa sprzętu')),
                ('location_category', models.CharField(choices=[('WAREHOUSE', 'Magazyn'), ('LAB', 'Laboratoria'), ('EMPLOYEE', 'Pracownicy')], default='WAREHOUSE', help_text='Określa, w której zakładce ma się domyślnie pojawiać karta.', max_length=20, verbose_name='Zakładka (Magazyn/Laboratoria/Pracownicy)')),
                ('building', models.CharField(blank=True, help_text='Np. 30, 40 itd.', max_length=10, verbose_name='Budynek')),
                ('room', models.CharField(blank=True, help_text='Np. 321, 511 itd.', max_length=20, verbose_name='Pomieszczenie')),
                ('unit_serial_number', models.CharField(blank=True, max_length=100, verbose_name='Nr seryjny jednostki')),
                ('monitor_serial_number', models.CharField(blank=True, max_length=100, verbose_name='Nr seryjny monitora')),
                ('unit_id', models.CharField(blank=True, max_length=50, verbose_name='ID jednostki')),
                ('monitor_id', models.CharField(blank=True, max_length=50, verbose_name='ID monitora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('mac_address', models.CharField(blank=True, max_length=50, verbose_name='Adres MAC')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Nazwa domenowa')),
                ('os_name', models.CharField(blank=True, help_text='Np. Windows 10 Pro, Windows 11, itp.', max_length=100, verbose_name='System operacyjny')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='Wersja systemu')),
                ('os_key', models.CharField(blank=True, help_text='Będzie przycisk KOPIUJ w interfejsie.', max_length=100, verbose_name='Klucz systemu Windows')),
                ('office_name', models.CharField(blank=True, help_text='Np. Office 2019, Office 365 itp.', max_length=100, verbose_name='MS Office – wersja')),
                ('office_key', models.CharField(blank=True, help_text='Będzie przycisk KOPIUJ w interfejsie.', max_length=100, verbose_name='MS Office – klucz')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data zakupu')),
                ('warranty_until', models.DateField(blank=True, help_text='Na podstawie tej daty w UI pokażemy: AKTYWNA / WYGASŁA.', null=True, verbose_name='Gwarancja do')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Dostawca')),
                ('status', models.CharField(choices=[('WAREHOUSE', 'Na magazynie'), ('IN_USE', 'W użyciu'), ('SERVICE', 'Serwis'), ('LOANED', 'Wypożyczony')], default='WAREHOUSE', max_length=20, verbose_name='Status')),
                ('loaned_to', models.CharField(blank=True, help_text='Wypełniane tylko gdy status = Wypożyczony.', max_length=255, verbose_name='Wypożyczony komu')),
                ('user_full_name', models.CharField(blank=True, max_length=255, verbose_name='Użytkownik (nazwisko i imię)')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Zdjęcie sprzętu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia modyfikacja')),
                ('last_modified_by', models.CharField(blank=True, help_text='Na później – będziemy tu zapisywać zalogowanego użytkownika.', max_length=150, verbose_name='Ostatnio edytował')),
            ],
            options={
                'verbose_name': 'Karta sprzętu',
                'verbose_name_plural': 'Karty sprzętu',
                'ordering': ['inventory_number'],
            },
        ),
    ]
