# Generated by Django 5.1.3 on 2025-12-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='loaned_to',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location_category',
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_tab',
            field=models.CharField(choices=[('MAGAZYN', 'Magazyn'), ('LAB', 'Laboratoria'), ('EMP', 'Pracownicy')], default='MAGAZYN', help_text='Określa, czy karta widnieje w zakładce Magazyn / Laboratoria / Pracownicy.', max_length=16, verbose_name='Zakładka lokalizacji'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='office_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='MS Office – wersja'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status_details',
            field=models.CharField(blank=True, help_text='Np. numer zgłoszenia serwisowego, komu wypożyczono itp.', max_length=255, verbose_name='Status – szczegóły'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.CharField(blank=True, help_text='Np. 30, 40 – pobierane z Excela z kolumny budynek / zakład.', max_length=16, verbose_name='Budynek'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(help_text="Np. Lenovo P360, Dell OptiPlex, IIYAMA 24'' itp.", max_length=255, verbose_name='Nazwa sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('SET', 'Zestaw komputerowy'), ('UNIT', 'Jednostka'), ('MONITOR', 'Monitor'), ('LAPTOP', 'Laptop'), ('PROJECTOR', 'Rzutnik / Projektor'), ('ACCESSORY', 'Akcesoria'), ('OTHER', 'Inny sprzęt')], default='SET', max_length=16, verbose_name='Rodzaj sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa domenowa (hostname)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(help_text='Np. 30181700000 – wspólny numer dla zestawu / jednostki / monitora.', max_length=32, unique=True, verbose_name='Numer inwentarzowy (11 cyfr)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_modified_by',
            field=models.CharField(blank=True, help_text='Na później – można tu zapisywać zalogowanego użytkownika.', max_length=150, verbose_name='Ostatnio edytował'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Adres MAC jednostki – z Excela, jeśli dostępny.', max_length=64, verbose_name='Adres MAC'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='monitor_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID monitora'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='monitor_serial_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nr seryjny monitora'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Dowolne uwagi dotyczące sprzętu.', verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_key',
            field=models.CharField(blank=True, help_text='Produkt key do Office – z możliwością kopiowania w karcie sprzętu.', max_length=255, verbose_name='Klucz MS Office'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_name',
            field=models.CharField(blank=True, help_text='Np. Office 2019, Office 365, itp.', max_length=128, verbose_name='MS Office – nazwa'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_key',
            field=models.CharField(blank=True, help_text='Produkt key do Windows – z możliwością kopiowania w karcie sprzętu.', max_length=255, verbose_name='Klucz systemu (Windows)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_name',
            field=models.CharField(blank=True, help_text='Np. Windows 10 Pro, Windows 11, itp.', max_length=128, verbose_name='System operacyjny'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='Wersja systemu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, help_text="Np. 321, 511 – tylko cyfry, bez 's.' itp.", max_length=32, verbose_name='Pomieszczenie / Sala'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('MAGAZYN', 'Na magazynie'), ('IN_USE', 'W użyciu'), ('SERVICE', 'W serwisie / naprawie'), ('BORROWED', 'Wypożyczony'), ('OTHER', 'Inny')], default='MAGAZYN', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, help_text='Firma, od której kupiono sprzęt – pomocne przy serwisie.', max_length=255, verbose_name='Dostawca sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID jednostki'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit_serial_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nr seryjny jednostki'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user_full_name',
            field=models.CharField(blank=True, help_text='Informacyjnie – kto używa sprzętu.', max_length=255, verbose_name='Użytkownik (nazwisko i imię)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_until',
            field=models.DateField(blank=True, help_text='Na podstawie tej daty wyliczamy czy gwarancja jest aktywna.', null=True, verbose_name='Gwarancja do'),
        ),
    ]
