# Generated by Django 5.1.3 on 2025-12-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_loaned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(help_text='Np. 30181700000 – wspólny numer dla zestawu / jednostki / monitora.', max_length=32, unique=True, verbose_name='Numer inwentarzowy'),
        ),
    ]
