# Generated by Django 5.1.3 on 2025-12-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_inventory_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='location_tab',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='monitor_id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='office_key',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='os_key',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status_details',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='equipment',
            name='borrowed_to',
            field=models.CharField(blank=True, help_text='Uzupełniasz ręcznie, gdy status = Wypożyczony.', max_length=255, verbose_name='Wypożyczony komu'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='office_serial_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Klucz MS Office'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='os_serial_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Klucz systemu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.CharField(blank=True, help_text='Np. 30, 40…', max_length=10, verbose_name='Budynek'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(blank=True, help_text='Opis / nazwa zestawu z Excela.', max_length=255, verbose_name='Nazwa sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('SET', 'Zestaw komputerowy'), ('PC', 'Komputer'), ('MONITOR', 'Monitor'), ('LAPTOP', 'Laptop'), ('PROJECTOR', 'Rzutnik'), ('ACCESSORY', 'Akcesoria'), ('OTHER', 'Inny sprzęt')], default='SET', max_length=20, verbose_name='Typ sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa domenowa'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(help_text='Numer z kolumny NR_INWENTARZOWY w Excelu.', max_length=20, unique=True, verbose_name='Numer inwentarzowy'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adres IP'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_modified_by',
            field=models.CharField(blank=True, help_text='Docelowo: login zalogowanego użytkownika.', max_length=150, verbose_name='Ostatnio edytował'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adres MAC'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='monitor_serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr seryjny monitora'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Tu ląduje zawartość kolumny UWAGI z Excela.', verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_name',
            field=models.CharField(blank=True, help_text='Np. Office', max_length=100, verbose_name='MS Office'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wersja MS Office'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_name',
            field=models.CharField(blank=True, help_text='Np. Windows', max_length=100, verbose_name='System operacyjny'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_version',
            field=models.CharField(blank=True, help_text='Np. 10, 11…', max_length=100, verbose_name='Wersja systemu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, help_text='Np. 321, 511…', max_length=20, verbose_name='Pomieszczenie'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('STOCK', 'Na magazynie'), ('IN_USE', 'W użyciu'), ('SERVICE', 'Serwis'), ('BORROWED', 'Wypożyczony')], default='STOCK', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dostawca sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit_serial_number',
            field=models.CharField(blank=True, help_text='Z kolumny NR_FABR (jeśli jest).', max_length=100, verbose_name='Nr seryjny jednostki'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Użytkownik (nazwisko i imię)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Gwarancja do'),
        ),
        migrations.CreateModel(
            name='EquipmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='equipment_attachments/', verbose_name='Plik')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Opis (opcjonalnie)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='equipment.equipment', verbose_name='Karta sprzętu')),
            ],
            options={
                'verbose_name': 'Załącznik',
                'verbose_name_plural': 'Załączniki',
            },
        ),
    ]
