# Generated by Django 5.1.3 on 2025-12-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_location_tab_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='borrowed_to',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Wypożyczono do'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Budynek'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nazwa sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Typ sprzętu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nazwa domenowa'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numer inwentarzowy'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Adres IP'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Ostatnio modyfikował'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Adres MAC'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='monitor_serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nr seryjny monitora'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pakiet Office'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_serial_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Klucz MS Office'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office_version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Wersja Office'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='System operacyjny'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_serial_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Klucz systemu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Wersja systemu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pomieszczenie'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dostawca'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit_serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nr seryjny jednostki'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Użytkownik (nazwisko i imię)'),
        ),
    ]
