# Generated by Django 5.1.3 on 2025-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_equipment_created_at_remove_equipment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakupu'),
        ),
    ]
