# Generated by Django 5.1.3 on 2025-12-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data ostatniej modyfikacji'),
        ),
    ]
