# Generated by Django 5.1.3 on 2025-12-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_last_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ostatnia modyfikacja'),
        ),
    ]
