# Generated by Django 5.1.3 on 2025-12-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_last_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='room_category',
            field=models.CharField(choices=[('LAB', 'Lab. komputerowe'), ('SALA', 'Sala wykładowa'), ('POKOJ', 'Pokój'), ('INNE', 'Inne'), ('MAGAZYN', 'Magazyn')], default='MAGAZYN', max_length=20, verbose_name='Kategoria pomieszczenia'),
        ),
    ]
