# Generated by Django 5.1.3 on 2025-12-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('has_space_mouse', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('unknown', 'Unknown'), ('not_installed', 'Not installed')], default='installed', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_software.laboratory')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_software.software')),
            ],
            options={
                'indexes': [models.Index(fields=['software', 'laboratory'], name='educational_softwar_3ba9dd_idx'), models.Index(fields=['laboratory', 'status'], name='educational_laborat_d9cf5d_idx')],
                'unique_together': {('software', 'laboratory')},
            },
        ),
    ]
